import React from 'react';
import { useTranslation } from 'react-i18next';
import { Helmet } from 'react-helmet';
import { Link } from 'react-router-dom';

const RefundPolicy = () => {
  const { t } = useTranslation('common');
  
  return (
    <div className="bg-white">
      <Helmet>
        <title>{t('footer.refund')} | iMagenWiz</title>
        <meta name="description" content="Refund Policy for iMagenWiz" />
      </Helmet>
      
      <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-extrabold text-gray-900 mb-8">{t('footer.refund')}</h1>
        
        <div className="prose prose-teal max-w-none">
          <p className="text-lg mb-6">Last updated: April 19, 2025</p>
          
          <p>
            If you are not 100% satisfied with your purchase, please contact us.
          </p>
          
          <h2 className="text-xl font-bold mt-8 mb-4">14 Days Money Back Guarantee</h2>
          
          <p>
            The 14 Days Money Back Guarantee applies if ...
          </p>
          
          <ul className="list-disc pl-6 mb-4">
            <li>you have purchased a subscription for the first time,</li>
            <li>the subscription was purchased within the last 14 days,</li>
            <li>you are not satisfied with the result quality and have no use for cut out images generated by imagenwiz.com,</li>
            <li>you have processed a total of less than 50 images in any resolution, and</li>
            <li>your account, you personally and your company have not made use of the 14 Days Money Back Guarantee before.</li>
          </ul>
          
          <p>
            To place a refund request, you would need to contact us using this <Link to="/contact" className="text-teal-600 hover:text-teal-800 font-medium">form</Link>. We will then review your request within 10 days and contact you via email.
          </p>
          
          <h2 className="text-xl font-bold mt-8 mb-4">Other Refunds</h2>
          
          <p>
            Purchases outside of the 14 Days Money Back Guarantee are generally non-refundable. If you are unhappy with your subscription you can cancel it any time. If you have any questions, feel free to <Link to="/contact" className="text-teal-600 hover:text-teal-800">contact us</Link>.
          </p>
        </div>
      </div>
    </div>
  );
};

export default RefundPolicy;